Update models.py
Deltares/HYDROLIB-core pull request #349
Opened 2022-10-03 11:02 UTC by veenstrajelmer

AutoStart type should be int instead of bool, since 2 is also a allowed value according to the manual: https://content.oss.deltares.nl/delft3d/manuals/D-Flow_FM_User_Manual.pdf#section.A.1

2022-10-04 11:40 UTC, priscavdsluis requested changes
@veenstrajelmer, I reviewed the changes. Please let me know what you think.

2022-10-04 11:40 UTC, priscavdsluis commented on hydrolib/core/io/mdu/models.py
> +    autostart: int = Field(0, alias="autoStart")
We also like to use enums for limited options such as in this case. 
This comes with the advantage that we can also document the several options. For example that `0` is `no`, `1` = `autostart` and `2` = `autostartstop`. 

I _think_ (not sure) that we get also "free" validation on the values, for example that 3 or -1 is not valid.


```
class AutoStartOption(IntEnum):
    """
    Enum class containing the valid values for the AutoStart
    attribute in the [General][hydrolib.core.io.mdu.models.General] class.
    """
    no=0
    autostart=1
    autostartstop=2
```


```
autostart: AutoStartOption = Field(AutoStartOption.no, alias="autoStart")
```

2022-10-04 12:01 UTC, veenstrajelmer commented
Great, looks good.

2022-10-13 08:49 UTC, priscavdsluis commented on hydrolib/core/io/mdu/models.py
> +    processfluxintegration: Optional[ProcessFluxIntegration] = Field(
Good catch!

2022-10-13 08:50 UTC, merged