Feat/316 forcing vectorquantities
Deltares/HYDROLIB-core pull request #381
Opened 2022-10-20 11:39 UTC by arthurvd

Fixes #316.

2022-10-21 11:10 UTC, tim-vd-aardweg requested changes

2022-10-21 11:30 UTC, arthurvd commented on hydrolib/core/io/bc/models.py
> +    elementname: List[str]
It *should* be the same, but it's different lines in the input, therefore we store it in the (two) different objects, and let the validator do the validity checking. This already happens now, here:
```
            else:
                raise ValueError(
                    f"Not all quantity unit pairs were found for the elements in vectordefinition {vectordef}."
                )
```

2022-10-21 11:33 UTC, arthurvd commented on hydrolib/core/io/bc/models.py
> +from hydrolib.core.basemodel import BaseModel
Well spotted! I removed the second one. That was just a transitive second import of one and the same `hydrolib.core.basemodel.BaseModel`.

2022-10-21 11:54 UTC, arthurvd commented on tests/data/input/dflowfm_individual_files/FlowFM_boundaryconditions3d_and_vectors.bc
> +                       Function = harmonic
Good point, I removed this harmonic import and also added 2D/TimeSeries testcases for vector quantities in a new class `TestVectorBC`.

2022-10-24 08:00 UTC, arthurvd commented on hydrolib/core/io/bc/models.py
> +    @staticmethod
I agree. I have now moved this to `class VectorQUPValidation`.

2022-10-24 08:01 UTC, arthurvd commented on hydrolib/core/io/bc/models.py
> +        """Validates the given vector definition header lines from a .bc file
I have added "from scratch" unit tests in today's commit.

2022-10-24 08:02 UTC, arthurvd commented on hydrolib/core/io/bc/models.py
> +class VectorQuantityUnitPairs(BaseModel):
I understand the confusion: I named it like this because a single vector quantity has multiple quantity unit pairs for its elements.

2022-10-24 08:04 UTC, arthurvd commented on hydrolib/core/io/bc/models.py
> +        # If one quantity is "time", it must be the first one.
This is not required by D-HYDRO. We only use it in hydrolib-core as the only pragmatic way to detect where the vector elements start.

2022-10-25 08:50 UTC, tim-vd-aardweg approved these changes
Review OK! As discussed, I will create a separate issue for a refactoring of vector implementation.

2022-10-25 08:54 UTC, merged