Feature/unst 8490 621 extforce converter boundary condition
Deltares/HYDROLIB-core pull request #717
Opened 2024-11-25 14:39 UTC by MAfarrag

# Add Converter for the Boundary Condition quantities in the old external forcing file

## New Features
Now there is a boundary condition converter

## Design
- All the existing converters "initial condition, boundary condition, mete data" now exist in one file `hydrolib/tools/ext_old_to_new/converters.py` as there are a lot of similarities and most probably in the future they will be redesigned, or lots of the repeated lines will be moved upstream to the `BaseConverter` super class.
- The `ext_old_to_new` is redesigned and  replaced with the `ExternalForcingConverter` class
```
ExternalForcingConverter
|-__init__
|- read_old_file
|- update
|- save
|- extold_model
|- ext_model (setter and getter)
|- inifield_model (setter and getter)
|- structure_model (setter and getter)
``` 
- The backup parameter in the `hydrolib/tools/ext_old_to_new/utils.backup_file` funcion is remove as there is now need to enter the function if you actually do not want to backup you file (the function should be called only if you need its functionality) and the condition should be made in the calling script.

## Formating and Styling
- I added lots of formatters that helps to format your code locally before pushing to the `sonar` online tool, these formatter works standalone or with pre-commit hooks.
- The pre-commit hooks configuration file is not part of the repo for now.

## Testing
### Data
- `tests/data/input/boundary-conditions/old-external-boundary_condition_only.ext`
- `tests/data/input/dflowfm_individual_files/polylines/polyline-no-z-no-label.pli`
- `tests/data/input/dflowfm_individual_files/polylines/polyline-no-z-with-label.pli`
- `tests/data/input/dflowfm_individual_files/polylines/polyline-with-z-no-label.pli``
- `tests/data/input/dflowfm_individual_files/polylines/polyline-with-z-no-label.pliz`

### New Tests
- Creating subfolders in the testing directory to replicate the same subfolders/modules of the package. `tests/dflowfm/extold/test_boundary.py` .
- Create `tests/dflowfm/extold/test_boundary.py::TestBoundary::test_existing_file`.
- Test the polyline with different cases `tests/dflowfm/polyfile/test_polyline_models.py`, currently the polyline failes with the scientific notation, and reads only the the number of dimensions (2*2) will read only the first two numbers in the row even if there is a z, and the z value will only be read if the second dimension is 3 and the extension has to  be `.pliz` in the same time.
- create a test for the converter `tests/tools/test_converters.py::TestBoundaryConverter`.
- create tests for all the methods and properties in the `ExternalForcingConverter` class.

## Old errors
- Multiple uses of mutable objects like lists  `[]` as a default values was converted to `Field(default_factory=list)`

2024-12-09 15:02 UTC, arthurvd requested changes
Hi, see my various comments. Maybe we need to talk tomorrow about the (silly) difference between regular polylines and boundary polylines.

2024-12-11 13:38 UTC, MAfarrag commented on hydrolib/tools/ext_old_to_new/converters.py
> +        if hasattr(forcing, "extrapolation"):
converted the value as following 
```
if hasattr(forcing, "extrapolation"):
       block_data["extrapolationmethod"] = "yes" if forcing.extrapolation == 1 else "no"
```

2024-12-11 13:42 UTC, MAfarrag commented on hydrolib/tools/ext_old_to_new/main_converter.py
> +    def ext_model(self) -> FileModel:
the type check always refers to the superclass not the subclass, so if i make it ExtModel the syntax checker will refer to it as a wrong return type

2024-12-11 14:37 UTC, MAfarrag commented on hydrolib/tools/ext_old_to_new/main_converter.py
> +    def read_old_file(cls, extoldfile: PathOrStr) -> "ExternalForcingConverter":
Redesigned:
the `ExternalForcingConverter` class can be instantiated by `ExtOldModel` or a path to external forcing file and the `_read_old_file` now is used inside the constructor to read the external forcing file if path is given to the converter

2024-12-11 14:39 UTC, MAfarrag commented on pyproject.toml
> +#[tool.poetry.group.docs.dependencies]
updated

2024-12-11 14:43 UTC, MAfarrag commented on pyproject.toml
> +reorder-python-imports = "^3.8.2"
removed

2024-12-11 14:51 UTC, MAfarrag commented on tests/data/input/dflowfm_individual_files/polylines/polyline-no-z-with-label.pli
renamed

2024-12-11 15:06 UTC, MAfarrag reviewed
.

2024-12-12 10:54 UTC, arthurvd commented on hydrolib/tools/ext_old_to_new/converters.py
> +        into a Meteo object. The Meteo object is suitable for use in new
@MAfarrag: this point is still open/unresolved.

2024-12-12 14:28 UTC, MAfarrag commented on hydrolib/tools/ext_old_to_new/main_converter.py
> +    ) -> Union[Tuple[FileModel, FileModel, FileModel], None]:
this is now fixed

2025-01-07 09:44 UTC, arthurvd approved these changes

2025-01-07 09:49 UTC, merged