Parameters Converter
Deltares/HYDROLIB-core pull request #718
Opened 2024-12-05 11:49 UTC by MAfarrag

2025-01-06 14:28 UTC, arthurvd requested changes
Functionally it looks good. See my individual comments for some code considerations.

2025-01-06 14:28 UTC, arthurvd commented on hydrolib/tools/ext_old_to_new/converters.py
> +def create_convert_inputs(forcing: ExtOldForcing) -> Dict[str, str]:
Make the function name more descriptive + add docstring (I can reverse engineer that this one is probably shared functionality for initial and parameter fields (i.e., it is intended to produce a dict that can be used to construct an instance of some AbstractSpatialField subclass.)

2025-01-06 14:28 UTC, arthurvd commented on hydrolib/tools/ext_old_to_new/converters.py
> +        """Convert an old external forcing block with meteo data to a boundary
docstring is (again ;-)) copy-past error from meteo.

2025-01-06 14:28 UTC, arthurvd commented on hydrolib/tools/ext_old_to_new/converters.py
> +            Boundary: A Boindary object that represents the converted forcing
typo

2025-01-06 14:28 UTC, arthurvd commented on tests/tools/test_converters.py
> +        assert new_quantity_block.interpolationmethod == "linearSpaceTime"
Would you not prefer:
```suggestion
        assert new_quantity_block.interpolationmethod == MeteoInterpolationMethod.linearSpaceTime        
```
and similar for all other enum values in the above assertions?

2025-01-06 21:13 UTC, MAfarrag commented on .github/pull_request_template.md
- When merged to the main branch, it will be used automatically when you create a merge request
- Should i remove it from here?

2025-01-06 21:16 UTC, MAfarrag commented on .github/pull_request_template.md
> +## Type of change
just in case we needed to go back to any merge request and reopen it for any reason, all the needed information should be stored here in the merge

2025-01-07 07:51 UTC, arthurvd commented on .github/pull_request_template.md
No need to remove now, but please take that approach in all future work :-)
regarding template and main: all clear!

2025-01-07 08:05 UTC, arthurvd approved these changes
I made some last fixes myself, all good now.

2025-01-07 13:10 UTC, merged