Feature/unst 8528 sources sinks converter
Deltares/HYDROLIB-core pull request #721
Opened 2024-12-12 10:13 UTC by MAfarrag

2025-01-08 13:55 UTC, arthurvd requested changes
See my individual remarks. I will review still a bit more in depth too.

2025-01-08 13:55 UTC, arthurvd commented on hydrolib/core/dflowfm/ext/models.py
> +    discharge: Union[float, List[float]] = Field(alias="discharge")
```suggestion
    discharge: ForcingData = Field(alias="discharge")
```
with top import:
```python
from hydrolib.core.dflowfm.bc.models import ForcingData
```

2025-01-08 13:55 UTC, arthurvd commented on hydrolib/core/dflowfm/ext/models.py
> +    temperaturedelta: Optional[Union[List[float], float]] = Field(
Also use type `ForcingData` instead of the custom Union,

2025-01-08 13:55 UTC, arthurvd commented on hydrolib/core/dflowfm/ext/models.py
> +    operand: Optional[Operand] = Field(Operand.override.value, alias="operand")
These should both be removed.

2025-01-08 13:55 UTC, arthurvd commented on hydrolib/core/dflowfm/ext/models.py
> +    def _exclude_from_validation(cls, input_data: Optional = None) -> Set:
```suggestion
    def _exclude_from_validation(cls, input_data: Optional[dict] = None) -> Set:
```

2025-01-08 13:55 UTC, arthurvd commented on hydrolib/core/dflowfm/ini/util.py
> +            data:
empty docstring

2025-01-08 13:55 UTC, arthurvd commented on hydrolib/core/dflowfm/polyfile/models.py
> +    def x(self) -> List[float]:
What is this used for? You typically want to keep the individual PolyObjects separated.

2025-01-08 13:55 UTC, arthurvd commented on hydrolib/core/dflowfm/polyfile/models.py
> +            if has_data:
Also safeguard against `not have_z`

2025-01-09 09:18 UTC, MAfarrag commented on hydrolib/core/dflowfm/polyfile/models.py
> +    def x(self) -> List[float]:
It is used in the `SourceSinkConverter.convert` to to get the xcoordinates

2025-01-09 09:21 UTC, MAfarrag commented on hydrolib/core/dflowfm/polyfile/models.py
> +            if has_data:
there is a property `has_z_value` which can be used outside the method where the user can know if the polyline has a z value if yes the get_zsource_sink then can be used

2025-01-09 09:42 UTC, MAfarrag commented on hydrolib/core/dflowfm/polyfile/models.py
> +            if has_data:
Now the `get_z_sources_sinks` will return a `[None], [None]` if the polyline does not have a z value as the `get_z_sources_sinks` just calls the `point.z` and for a polyline that does not have a z value the z value is assigned to None

2025-01-09 09:44 UTC, MAfarrag commented on hydrolib/core/dflowfm/polyfile/models.py
> +            if has_data:
I have added documentation (Note in the `PolyFile.get_zsources_sinks`, also an examples) and a test `tests/dflowfm/poolyfole/test_polyline_models.py::TestGetZSourcesSinks.test_get_z_sources_sinks_no_z_values`

2025-01-09 14:26 UTC, MAfarrag commented on hydrolib/core/dflowfm/ext/models.py
> +    temperaturedelta: Optional[Union[List[float], float]] = Field(
The `ForcingData` class did not have a `List[float]` so now I used it after i added `List[float]` to it

2025-01-09 14:58 UTC, MAfarrag commented on hydrolib/tools/ext_old_to_new/converters.py
> +        - salinitydelta (optional)
Done.
So now the salinity is at the 3rd column, and temperature is at the 4th column.

2025-01-10 13:13 UTC, MAfarrag commented on hydrolib/tools/ext_old_to_new/converters.py
> +        - the function will raise a `ValueError` if the temperature and salinity are present in the MDU file (value
fixed

2025-01-10 13:14 UTC, MAfarrag commented on hydrolib/tools/ext_old_to_new/converters.py
> +        - the function will raise a `ValueError` if the temperature and salinity are present in the MDU file (value
Notes:
      - The function will combine the temperature and salinity from the MDU file (value is 1) file with the
                quantities mentioned in the external forcing file, and will get the list of quantities that are in the tim file.
      - The function will return a dictionary with the quantities as keys and the time series data as values.

2025-01-13 12:21 UTC, arthurvd requested changes
Hi @MAfarrag, thanks for all the fixes. Only a few minor typing thingies left. Almost ready to merge.

2025-01-13 12:21 UTC, arthurvd commented on hydrolib/core/dflowfm/bc/models.py
> +ForcingData = Union[float, List[float], RealTime, ForcingModel]
Where do you need a List of floats on a forcingData line?
(May the confusion came from `SourceSink.zsource` (which indeed may be a list of two floats), but that is no forcingData. So, can we get rid of it here?

2025-01-13 12:21 UTC, arthurvd commented on hydrolib/core/dflowfm/ext/models.py
> +    temperaturedelta: Optional[Union[List[float], float]] = Field(
See my new remark over there for forcingData.

2025-01-13 12:21 UTC, arthurvd commented on hydrolib/core/dflowfm/polyfile/models.py
> +            z_source, z_sinkA: Tuple[List[float]]:
I believe this now (wrongly) annotates a tuple with only 1 element (which is itself a list of floats).
The correct annotation is either `Tuple[List[float], List[float]]`, or a bit more freely:
`Tuple[List[float], ...]`
Quoting https://docs.python.org/3/library/typing.html#annotating-tuples :
> To denote a tuple which could be of any length, and in which all elements are of the same type `T`, use `tuple[T, ...]`

(also fix line 147 above)

2025-01-13 15:20 UTC, MAfarrag commented on hydrolib/core/dflowfm/bc/models.py
> +ForcingData = Union[float, List[float], RealTime, ForcingModel]
The `discharge`, `temperaturedelta`, `salinitydelta` you suggested to use `ForcingData` class with those instead of the `Union[float, List[float]]`

2025-01-13 15:21 UTC, MAfarrag commented on hydrolib/core/dflowfm/bc/models.py
> +ForcingData = Union[float, List[float], RealTime, ForcingModel]
here https://github.com/Deltares/HYDROLIB-core/pull/721#discussion_r1907148543

2025-01-13 15:21 UTC, MAfarrag commented on hydrolib/core/dflowfm/ext/models.py
> +    discharge: Union[float, List[float]] = Field(alias="discharge")
here

2025-01-13 15:24 UTC, MAfarrag commented on hydrolib/core/dflowfm/polyfile/models.py
> +            z_source, z_sinkA: Tuple[List[float]]:
corrected

2025-01-14 08:29 UTC, arthurvd commented on hydrolib/core/dflowfm/bc/models.py
> +ForcingData = Union[float, List[float], RealTime, ForcingModel]
As discussed: only list[float] can still go, because the ForcingModel stores an entire .bc file, which is all we need for timeseries.

2025-01-15 11:06 UTC, MAfarrag commented on hydrolib/core/dflowfm/ext/models.py
> +    discharge: Union[float, List[float]] = Field(alias="discharge")
this is now back to Union[float, List[floats]]

2025-01-15 11:06 UTC, MAfarrag commented on hydrolib/core/dflowfm/ext/models.py
> +    temperaturedelta: Optional[Union[List[float], float]] = Field(
this is now back to Union[float, List[floats]] and will be changes to use `forcingData` in a separate merge

2025-01-15 11:08 UTC, MAfarrag commented on hydrolib/core/dflowfm/bc/models.py
> +ForcingData = Union[float, List[float], RealTime, ForcingModel]
this is now back to Union[float, List[floats]] and will be changes to use `forcingData` in a separate merge

2025-01-15 14:00 UTC, arthurvd approved these changes
As discussed: this part of the source sink converter is now OK.
The tim to BC converter part will continue in a separate issue + branch (UNST-8553).

2025-01-15 14:14 UTC, merged